(ns cljs-intro.stories)

(def catch-phrases ["adaptive" "advanced" "ameliorated" "assimilated" "automated" "balanced" "business-focused" "centralized" "cloned" "compatible" "configurable" "cross-group" "cross-platform" "customer-focused" "customizable" "decentralized" "de-engineered" "devolved" "digitized" "distributed" "diverse" "down-sized" "enhanced" "enterprise-wide" "ergonomic" "exclusive" "expanded" "extended" "face to face" "focused" "front-line" "fully-configurable" "function-based" "fundamental" "future-proofed" "grass-roots" "horizontal" "implemented" "innovative" "integrated" "intuitive" "inverse" "managed" "mandatory" "monitored" "multi-channelled" "multi-lateral" "multi-layered" "multi-tiered" "networked" "object-based" "open-architected" "open-source" "operative" "optimized" "optional" "organic" "organized" "persevering" "persistent" "phased" "polarised" "pre-emptive" "proactive" "profit-focused" "profound" "programmable" "progressive" "public-key" "quality-focused" "reactive" "realigned" "re-contextualized" "re-engineered" "reduced" "reverse-engineered" "right-sized" "robust" "seamless" "secured" "self-enabling" "sharable" "stand-alone" "streamlined" "switchable" "synchronised" "synergistic" "synergized" "team-oriented" "total" "triple-buffered" "universal" "up-sized" "upgradable" "user-centric" "user-friendly" "versatile" "virtual" "visionary" "vision-oriented"])
(def catch-phrase-desc ["24 hour" "24/7" "3rd generation" "4th generation" "5th generation" "6th generation" "actuating" "analyzing" "assymetric" "asynchronous" "attitude-oriented" "background" "bandwidth-monitored" "bi-directional" "bifurcated" "bottom-line" "clear-thinking" "client-driven" "client-server" "coherent" "cohesive" "composite" "context-sensitive" "contextually-based" "content-based" "dedicated" "demand-driven" "didactic" "directional" "discrete" "disintermediate" "dynamic" "eco-centric" "empowering" "encompassing" "even-keeled" "executive" "explicit" "exuding" "fault-tolerant" "foreground" "fresh-thinking" "full-range" "global" "grid-enabled" "heuristic" "high-level" "holistic" "homogeneous" "human-resource" "hybrid" "impactful" "incremental" "intangible" "interactive" "intermediate" "leading edge" "local" "logistical" "maximized" "methodical" "mission-critical" "mobile" "modular" "motivating" "multimedia" "multi-state" "multi-tasking" "national" "needs-based" "neutral" "next generation" "non-volatile" "object-oriented" "optimal" "optimizing" "radical" "real-time" "reciprocal" "regional" "responsive" "scalable" "secondary" "solution-oriented" "stable" "static" "systematic" "systemic" "system-worthy" "tangible" "tertiary" "transitional" "uniform" "upward-trending" "user-facing" "value-added" "web-enabled" "well-modulated" "zero administration" "zero defect" "zero tolerance"])
(def noun ["ability" "access" "adapter" "algorithm" "alliance" "analyzer" "application" "approach" "architecture" "archive" "artificial intelligence" "array" "attitude" "benchmark" "budgetary management" "capability" "capacity" "challenge" "circuit" "collaboration" "complexity" "concept" "conglomeration" "contingency" "core" "customer loyalty" "database" "data-warehouse" "definition" "emulation" "encoding" "encryption" "extranet" "firmware" "flexibility" "focus group" "forecast" "frame" "framework" "function" "functionalities" "Graphic Interface" "groupware" "Graphical User Interface" "hardware" "help-desk" "hierarchy" "hub" "implementation" "info-mediaries" "infrastructure" "initiative" "installation" "instruction set" "interface" "internet solution" "intranet" "knowledge user" "knowledge base" "local area network" "leverage" "matrices" "matrix" "methodology" "middleware" "migration" "model" "moderator" "monitoring" "moratorium" "neural-net" "open architecture" "open system" "orchestration" "paradigm" "parallelism" "policy" "portal" "pricing structure" "process improvement" "product" "productivity" "project" "projection" "protocol" "secured line" "service-desk" "software" "solution" "standardization" "strategy" "structure" "success" "superstructure" "support" "synergy" "system engine" "task-force" "throughput" "time-frame" "toolset" "utilisation" "website" "workforce"])
(def verbs ["Implement" "Utilize" "Integrate" "Streamline" "Optimize" "Evolve" "Transform" "Embrace" "Enable" "Orchestrate" "Leverage" "Reinvent" "Aggregate" "Architect" "Enhance" "Incentivize" "Morph" "Empower" "Envisioneer" "Monetize" "Harness" "Facilitate" "Seize" "Disintermediate" "Synergize" "Strategize" "Deploy" "Brand" "Grow" "Target" "Syndicate" "Synthesize" "Deliver" "Mesh" "Incubate" "Engage" "Maximize" "Benchmark" "Expedite" "Reintermediate" "Whiteboard" "Visualize" "Repurpose" "Innovate" "Scale" "Unleash" "Drive" "Extend" "Engineer" "Revolutionize" "Generate" "Exploit" "Transition" "E-enable" "Iterate" "Cultivate" "Matrix" "Productize" "Redefine" "Recontextualize"])
(def buzz ["clicks-and-mortar" "value-added" "vertical" "proactive" "robust" "revolutionary" "scalable" "leading-edge" "innovative" "intuitive" "strategic" "e-business" "mission-critical" "sticky" "one-to-one" "24/7" "end-to-end" "global" "B2B" "B2C" "granular" "frictionless" "virtual" "viral" "dynamic" "24/365" "best-of-breed" "killer" "magnetic" "bleeding-edge" "web-enabled" "interactive" "dot-com" "sexy" "back-end" "real-time" "efficient" "front-end" "distributed" "seamless" "extensible" "turn-key" "world-class" "open-source" "cross-platform" "cross-media" "synergistic" "bricks-and-clicks" "out-of-the-box" "enterprise" "integrated" "impactful" "wireless" "transparent" "next-generation" "cutting-edge" "user-centric" "visionary" "customized" "ubiquitous" "plug-and-play" "collaborative" "compelling" "holistic" "rich"])
(def bs-noun ["synergies" "web-readiness" "paradigms" "markets" "partnerships" "infrastructures" "platforms" "initiatives" "channels" "eyeballs" "communities" "ROI" "solutions" "e-tailers" "e-services" "action-items" "portals" "niches" "technologies" "content" "vortals" "supply-chains" "convergence" "relationships" "architectures" "interfaces" "e-markets" "e-commerce" "systems" "bandwidth" "infomediaries" "models" "mindshare" "deliverables" "users" "schemas" "networks" "applications" "metrics" "e-business" "functionalities" "experiences" "web services" "methodologies"])

(def sentence-components [verbs catch-phrases catch-phrase-desc buzz bs-noun])

(defn rand-sentence []
  (clojure.string/join " "
    (map rand-nth sentence-components)))